comment추가

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -19,13 +19,20 @@ jobs:
           cd packages/assignment-6
           npx tsc
           npm run build
-        continue-on-error: true
+        if: failure()
+      - name: Run TypeScript compiler and Build
+        id: build
+        run: |
+          output=$(npx tsc 2>&1 && npm run build 2>&1) || echo "::set-output name=error::$output"
+
 
   lint:
     runs-on: ubuntu-latest
     steps:
       - name: job2 구현
-        run: echo "job2의 내용을 구현해주세요"
+        run: | 
+          npm ci
+          npm run lint
 
   test:
     runs-on: ubuntu-latest
